### ISSUE TITLE
Add Embedding API Support

### ISSUE THREAD

**Issue by h0rv** [IBM/watsonx-go#9]
https://cloud.ibm.com/apidocs/watsonx-ai#text-embeddings

**Comment by PabloSanchi** [comment]
Has this issue already been addressed? 

If not, I already did this integration to Java Spring AI project, so I am more than happy to address this issue as well :)

**Comment by h0rv** [comment]
@PabloSanchi this has not been addressed - I'll assign you the issue. Thanks! 😃
